//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace  ACG.EA.AppCentre.Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_LOG
    {
        public int ACTIVITY_LOG_ID { get; set; }
        public string USER_NAME { get; set; }
        public string APPLICATION_NAME { get; set; }
        public string TARGET_VALUE { get; set; }
        public System.DateTime ACTIVITY_DATE { get; set; }
    }
}
