//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace  ACG.EA.AppCentre.Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_GROUP
    {
        public APPLICATION_GROUP()
        {
            this.GROUP_PERMISSION = new HashSet<GROUP_PERMISSION>();
            this.USER_APPLICATION_GROUP = new HashSet<USER_APPLICATION_GROUP>();
        }
    
        public string GROUP_ID { get; set; }
        public string APPLICAITON_ID { get; set; }
        public string GROUP_NAME { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
        public virtual ICollection<GROUP_PERMISSION> GROUP_PERMISSION { get; set; }
        public virtual ICollection<USER_APPLICATION_GROUP> USER_APPLICATION_GROUP { get; set; }
    }
}
