//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace  ACG.EA.AppCentre.Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOG
    {
        public CATALOG()
        {
            this.APPLICATIONs = new HashSet<APPLICATION>();
        }
    
        public string CATALOG_ID { get; set; }
        public string CATALOG_NAME { get; set; }
    
        public virtual ICollection<APPLICATION> APPLICATIONs { get; set; }
    }
}
