//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACG.EA.AppCentre.Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION
    {
        public PERMISSION()
        {
            this.GROUP_PERMISSION = new HashSet<GROUP_PERMISSION>();
            this.USER_PERMISSION = new HashSet<USER_PERMISSION>();
        }
    
        public string PERMISSION_ID { get; set; }
        public string APPLICATION_ID { get; set; }
        public Nullable<int> TARGET_ID { get; set; }
        public string PERMISSION_NAME { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
        public virtual ICollection<GROUP_PERMISSION> GROUP_PERMISSION { get; set; }
        public virtual TARGET TARGET { get; set; }
        public virtual ICollection<USER_PERMISSION> USER_PERMISSION { get; set; }
    }
}
