//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACG.EA.AppCentre.Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_APPLICATION_GROUP
    {
        public int USER_APPLICATION_GROUP_ID { get; set; }
        public int USER_ID { get; set; }
        public string GROUP_ID { get; set; }
        public string APPLICATION_ID { get; set; }
    
        public virtual APPLICATION_GROUP APPLICATION_GROUP { get; set; }
        public virtual USER USER { get; set; }
    }
}
