//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACG.EA.AppCentre.Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_USER_PERMISSION
    {
        public string USER_NAME { get; set; }
        public string APPLICATION_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public string PERMISSION_NAME { get; set; }
        public string VALUE { get; set; }
    }
}
